/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutTwitter: typeof import('./src/components/AboutTwitter.vue')['default']
    Appbar: typeof import('./src/components/Appbar.vue')['default']
    ExamCategory: typeof import('./src/components/ExamCategory.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeaderParallax: typeof import('./src/components/HeaderParallax.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
