/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/kakomon/': RouteRecordInfo<'/kakomon/', '/kakomon', Record<never, never>, Record<never, never>>,
    '/kakomon/AM-Question-overview': RouteRecordInfo<'/kakomon/AM-Question-overview', '/kakomon/AM-Question-overview', Record<never, never>, Record<never, never>>,
    '/kakomon/AP-AM': RouteRecordInfo<'/kakomon/AP-AM', '/kakomon/AP-AM', Record<never, never>, Record<never, never>>,
    '/kakomon/FE-AM': RouteRecordInfo<'/kakomon/FE-AM', '/kakomon/FE-AM', Record<never, never>, Record<never, never>>,
  }
}
